compiler:
  solc:
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.3.2"
      - "@chainlink=smartcontractkit/chainlink-brownie-contracts@0.2.2"
dependencies:
  # - <organization/repo>@<version>
  - OpenZeppelin/openzeppelin-contracts@4.3.2
  - smartcontractkit/chainlink-brownie-contracts@0.2.2
dotenv: .env
networks:
  default: development
  kovan:
    link_token_address: "0xa36085F69e2889c224210F603D836748e7dC0088"
    verify: True
  rinkeby:
    link_token_address: "0x01BE23585060835E02B77ef475b0Cc51aA1e0709"
    verify: True
